name: Compliance Automation CI

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * *'  # Runs daily at 2AM UTC

jobs:
  compliance:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pandas matplotlib

      - name: Run compliance scoring
        run: python3 scripts/compliance_scoring.py

      - name: Upload compliance artifacts
        uses: actions/upload-artifact@v4
        with:
          name: compliance_report
          path: |
            reports/compliance_report.html
            reports/bar_chart.png
            reports/trend_chart.png
