name: Compliance Automation CI

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 3 * * *"  # daily at 03:00 UTC
  workflow_dispatch:

jobs:
  compliance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas plotly

      - name: Ensure reports directory exists
        run: mkdir -p grc-compliance-automation/reports

      - name: Run compliance scoring
        run: python grc-compliance-automation/scripts/compliance_scoring.py

      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: compliance-report
          path: grc-compliance-automation/reports/compliance_report.html
